[package]
name = "dart-vm"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dart-sys = { path = "../dart-sys" }
log = "0.4"
